# Generated by Django 4.1.5 on 2023-01-12 02:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_form',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
