# Generated by Django 4.1.5 on 2023-01-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0002_remove_video_order_video_sim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='sim',
        ),
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
