# Generated by Django 4.1.5 on 2023-01-17 23:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0004_remove_video_description_video_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='order',
        ),
        migrations.AddField(
            model_name='video',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='video',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='video',
            name='email',
            field=models.EmailField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='video',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
