# Generated by Django 4.1.5 on 2023-01-17 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0005_remove_video_order_video_body_video_date_video_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='video',
            name='body',
        ),
        migrations.RemoveField(
            model_name='video',
            name='date',
        ),
        migrations.RemoveField(
            model_name='video',
            name='email',
        ),
        migrations.RemoveField(
            model_name='video',
            name='phone',
        ),
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
